spring:
    application:
        name: RobotFrontend

server:
    port: 8091
    error:
        include-stacktrace: always
        include-exception: true
        include-message: always
    whitelabel:
        enabled: false

robot:
    backend:
        root_url: http://127.0.0.1:8090

